[package]
name = "Actuate"
version = "1.4.5"
edition = "2021"
authors = ["Ardura <azviscarra@gmail.com>"]
license = "GPL-3.0-or-later"
homepage = "https://github.com/ardura"
description = "Sampler + Synth"

[workspace]
members = ["xtask"]

[lib]
crate-type = ["cdylib","lib"]

[dependencies]
hound = "3.5.0"
lazy_static = "1.4.0"

# Nih plug fork for actuate
nice-plug = { git = "https://codeberg.org/BillyDM/nice-plug.git", rev = "63fe31591220d71a0481534cbc4f0dc1be9ebf7b", features = ["assert_process_allocs"] }
nice-plug-egui = { git = "https://codeberg.org/BillyDM/nice-plug.git", rev = "63fe31591220d71a0481534cbc4f0dc1be9ebf7b" }

#nih_plug = { git = "https://github.com/Ardura/nih-plug.git", rev = "ce77d8c6daeebcdcc15e84a178ddce617ee6a3d3", features = ["assert_process_allocs"] }
#nih_plug_egui = { git = "https://github.com/Ardura/nih-plug.git", rev = "ce77d8c6daeebcdcc15e84a178ddce617ee6a3d3" }

num-complex = "0.4.4"
num-traits = "0.2.17"
once_cell = "1.18.0"
parking_lot = "0.12.1"
pitch_shift = "2.1.0"
rand = "0.10.1"
rand_pcg = "0.10.2"
serde = "1.0.188"
serde_json = "1.0.107"
dirs = "6.0.0"
walkdir = "2.5.0"
rayon = "1.10.0"
anyhow = "1.0.97"
ureq = { version = "3.0.10", features = ["json"] }
zip = "8.6.0"

[profile.release]
opt-level = 3
split-debuginfo = 'packed'
debug = false
debug-assertions = false
overflow-checks = false
lto = 'thin'
panic = 'unwind'
incremental = false
codegen-units = 1
rpath = false

[profile.profiling]
inherits = "release"
split-debuginfo = '...'
debug = true
rpath = false
lto = "off"
opt-level = 0
strip = "none"
